# Generated by Django 3.2.8 on 2021-10-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('jackets', 'Jackets'), ('jeans', 'Jeans'), ('shirts', 'Shirts'), ('shoes', 'Shoes'), ('tshirts', 'T-Shirts')], max_length=50, unique=True),
        ),
    ]
