# Generated by Django 3.2.8 on 2021-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Jackets', 'Jackets'), ('Jeans', 'Jeans'), ('Shirts', 'Shirts'), ('Shoes', 'Shoes'), ('T-Shirts', 'T-Shirts')], max_length=50, unique=True),
        ),
    ]
